### ISSUE TITLE
Question about potential addition...

### ISSUE THREAD

**Issue by telkins** [spatie/laravel-rate-limited-job-middleware#15]
@freekmurze I came across this while building a similar job middleware...but one for `Redis::funnel()`.  I was excited at first, and then lost a lot of that excitement when I realized that not only was there no funnel job middleware in this package, but that it might not be a possibility.

A lot of the code could just as easily be used for `Redis::funnel()`, but to add such a middleware to this package would make the name seem a bit odd.  To create a whole new package would mean repeating most of the functionality that is in this package.

So...I was wondering if you had any thoughts on what could be a good solution?  I'd like to create a funnelling job middleware, but would likely use a lot of what you've already done here.  It wouldn't be terribly DRY.  ;-)

Let me know what you think.  Thx.  :-)

**Comment by freekmurze** [comment]
I've never used that method, but looking at the [laravel docs on it](https://laravel.com/docs/5.8/queues#rate-limiting) it does something else then the rate limiting by this package. Using the funnel method you can specify how many workers can pick up a job, but not how many jobs should be processed within a timeframe. Do I interpret this correctly?

If so, then I think the best solution for you to just copy the package, rename it to whatever you think suits best, make the necessary adjustments, publish and maintain that on your own.

**Comment by telkins** [comment]
@freekmurze Yes, I think you're interpreting it correctly...at least, it's the same way I interpret it.  ;-)

Alright...I'll do what you suggested, then.  Much appreciated...!  :-)

**Comment by freekmurze** [comment]
When you finished your package, let me know, and I'll include a link to yours in our readme 👍

**Comment by telkins** [comment]
@freekmurze FYI...I just published the package: https://github.com/telkins/laravel-job-funneling-middleware

It's experimental, of course, mainly because I'm at a loss when it comes to testing.  I need to do some research and figure out how to test funnelling...!  :-0

Anyway, much appreciated.  I put a "Special Credit" section at the top, doffing my cap.  :-)

Thx.

**Comment by trevorgehman** [comment]
I feel like expanding this package to include `Redis::funnel` is a great idea. Instead of:

```
$rateLimitedMiddleware = (new RateLimited())
        ->allow(30)
        ->everySeconds(60);
```

You can specify:

```
$rateLimitedMiddleware = (new RateLimited())
        ->allow(30)
        ->atOnce();
```

There are some APIs that handle rate limiting based on concurrent requests, rather than number of requests per timeframe, such as [Salesforce](https://developer.salesforce.com/blogs/engineering/2013/05/force-com-concurrent-request-limits.html).

**Comment by trevorgehman** [comment]
MailChimp's API works the same way apparently. I've hit this error recently:

```
{
"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/",
"title":"Too Many Requests",
"status":429,
"detail":"You have exceeded the limit of 10 simultaneous connections.",
"instance":"fefeed9a-e0e4-4601-b995-b9c93a2bf472"
}
```

**Comment by telkins** [comment]
@trevorgehman Have you looked at this package: https://github.com/telkins/laravel-job-funneling-middleware

It's mostly a copy of this package with the relevant bits changed.  The problem is that the common code isn't reused and there aren't any tests.  I've been using it for a project and it seems to work fine.  Having some others looking at it would increase confidence, of course.

Ideally, it would "share the same space" as this package, I think, but if that's not going to happen....  ;-)
