### ISSUE TITLE
Documentation lists connectionName as connection

### ISSUE THREAD

**Issue by PunchRockgroin** [spatie/laravel-rate-limited-job-middleware#25]
In https://github.com/spatie/laravel-rate-limited-job-middleware#customizing-redis the setting for connection should be connectionName

https://github.com/spatie/laravel-rate-limited-job-middleware/blob/master/src/RateLimited.php#L50

Thanks!

**Comment by freekmurze** [comment]
Fixed! Feel free to PR further improvements.
