### ISSUE TITLE
"Redis is required"

### ISSUE THREAD

**Issue by bytestream** [spatie/laravel-rate-limited-job-middleware#56]
The readme states:
https://github.com/spatie/laravel-rate-limited-job-middleware/blob/4bf5777b31459d8bfd226a0661a3c153b2441b93/README.md?plain=1#L25

Unless I'm mistaken https://github.com/spatie/laravel-rate-limited-job-middleware/pull/32 implemented an option to use caching instead of Redis. Thus if you initialise `new RateLimited(false)` then Redis is not required.

**Comment by riasvdv** [comment]
You are right, removed that line!
